name: 'Release'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: 1.13.4
          otp-version: 24.1

      - name: Create Release Package
        run: mix hex.build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            underthehood-${{ github.ref_name }}.tar

      - name: Publish to Hex.pm
        run: mix deps.get && mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}


